name: Github Pages

on:
  workflow_dispatch:

env:
  VITE_BACKEND_URL: https://backend-v113.testnet.alephium.org
  VITE_NODE_URL: https://wallet-v20.testnet.alephium.org
  VITE_NETWORK_TYPE: testnet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: build
          clean: true # Automatically remove deleted files from the deploy branch
