name: Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm audit --production
      - run: npm run lint
      - run: npm run typecheck
