name: Static analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NPM dependencies
        run: pnpm install

      - name: Lint all workspaces in parallel
        run: pnpm run lint

      - name: Check that TypeScript compiles in all workspaces in parallel
        run: pnpm run typecheck

      - name: Audit NPM dependencies
        run: pnpm audit --prod
