name: Static analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo

      - name: Lint all workspaces in parallel
        run: pnpm run lint

      - name: Check that TypeScript compiles in all workspaces in parallel
        run: pnpm run typecheck

      - name: Audit NPM dependencies
        run: pnpm audit --prod
