name: Static analysis

on:
  push:
    branches: [master]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Bun package manager
        uses: oven-sh/setup-bun@v1

      - name: Install NPM dependencies
        run: bun install --yarn

      - name: Lint all workspaces in parallel
        run: bun run lint

      - name: Check that TypeScript compiles in all workspaces in parallel
        run: bun run typecheck

      - name: Change packageManager field in package.json from bun to yarn
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: packageManager
          value: yarn@1.22.21

      - name: Audit NPM dependencies
        run: yarn audit --production
